feign:
  client:
    config:
      getFeignClient:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL
        decoder: com.own.gameofthronesenlistment.enlistment.config.CustomDecoder


